name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.1
    - name: Create Build Directory
      run: mkdir build
    - name: Change to Build Directory and Build
      run: |
        cd build
        cmake ..
        cmake --build . --config Release
